### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by Himself65** [TexteaInc/json-viewer#1]
Upstream: https://github.com/mac-s-g/react-json-view/issues/121

We need JSON viewer in some of our cell types, but upstream has no longer been maintained.

**Comment by Himself65** [comment]
Could you please take a look at which module use the window?

/cc @exuanbo

**Comment by Himself65** [comment]
Seems like because https://github.com/Andarist/react-textarea-autosize

**Comment by exuanbo** [comment]
`Window` and `document` is referenced in function `getSizingData`.

https://github.com/Andarist/react-textarea-autosize/blob/cd87f81b94576fd66dd3f1e055af9157bd50d808/src/getSizingData.ts

Also, `useLayoutEffect` is used in hook `useWindowResizeListener`.

https://github.com/Andarist/react-textarea-autosize/blob/cd87f81b94576fd66dd3f1e055af9157bd50d808/src/hooks.ts

**Comment by Himself65** [comment]
https://github.com/Andarist/react-textarea-autosize/issues/335

**Comment by Himself65** [comment]
Fixed in `1.23.0-alpha.0`

**Comment by Himself65** [comment]
Closing as fixed in https://github.com/TexteaInc/json-viewer/releases/tag/v1.23.0
