### ISSUE TITLE
Add support for displayObjectSize

### ISSUE THREAD

**Issue by axelniklasson** [TexteaInc/json-viewer#101]
Hi! Thanks for working on this, this is a great alternative to https://github.com/mac-s-g/react-json-view 👍 

I was wondering if there are any plans to add support for the `displayObjectSize` prop that is available in the other library? I'd love to use this library in our product but I want to hide the size label for all objects in the JSON field, which would be done through setting `displayObjectSize: false` in the the old [project](https://github.com/mac-s-g/react-json-view#props).

**Comment by Himself65** [comment]
this could possible

**Comment by Himself65** [comment]
I'm thinking to add `props.features.displayObjectSize` because we would support much customizable stuff in the future.
