### ISSUE TITLE
enableClipboard doesn't accept callback

### ISSUE THREAD

**Issue by thameera** [TexteaInc/json-viewer#109]
The original repo (mac-s-g/react-json-view) lets you specify a callback for the `enableClipboard` attribute, in addition to boolean. This seems to be missing in this fork - any plans to support that?

This callback is useful for example to prevent quotes in strings from being copied - see https://github.com/mac-s-g/react-json-view/issues/217#issuecomment-459215632

**Comment by Himself65** [comment]
Im adding onCopy props
