### ISSUE TITLE
Roadmap for v2

### ISSUE THREAD

**Issue by Himself65** [TexteaInc/json-viewer#11]
our `@textea/json-viewer` is based on [mac-s-g/react-json-view](https://github.com/mac-s-g/react-json-view), which haven’t been maintained since about 2 years ago. Also, the way of writing a react component has changed since then. 

So, in `v2` version, we will firstly **rewrite** the whole project using `TypeScript` and `React Hooks`.

Secondly, our team’s product(closed alpha for now) is also using `json-viewer`, we need customize json style in many cases. We need also improve the styling system, my currently plan is to use `@mui/material` which is a popular library.

Third, is store, I’ve read the whole source code, the previous author stores a value using like`globalStore.set/get(randomID, key, value, defaultValue)` (https://github.com/mac-s-g/react-json-view/blob/master/src/js/stores/ObjectAttributes.js). Also, in many cases, many fields like `defaultValue` are bypass through the whole component lifecycle. We need refactor this part into a lightly structure using `ReactContext`, `Zustand`.

What’s more, a guy suggests me to support plugin system. I’m also thinking this at the beginning. I would prefer a API like:

```tsx
const types = {
  …jsonViewer.types,
  // support hook with your component
  Number: // MyNumberComponent
}
<JsonViewer
  types={types}
  keyRenderer=((paths: string[], value: unknown, type: Type) => { … })
  valueRenderer=((value: unknown, paths: string[], type: Type) => { … })
>
```

What’s more, I don’t want it just stop by a **JSON** viewer. In a real production, we will have many class instance or something more than a string, like images.

```tsx
const json = {
  type: ‘image’,
  image: ‘base64:xxx’,
  error: new Error(‘something not good’)
}

return (
<JsonViewer
  src={json}
  types={{
    …jsonViewer.types,
    Image: [
      (t) => isBase64(t), // whether this is a image
      (props) => <Image src={props.value}/> // load image
    ],
    Error: [
      (t) => t instanceof Error,
      props => props.value.message // fallback to ‘something not good’
    ]
  }}
/>
)
```

P.S. This is inspired by https://www.npmjs.com/package/typeson

## Related Issues

- [x] #10 
- [x] #2 
- [x] #3 
- [x] #23 
- [x] #24 
- [ ] #25

**Comment by Himself65** [comment]
Work steps:

1. Refactor every component to Function Component with TypeScript
2. Repleace base16-styling to mui
3. Use zustand

**Comment by awkj** [comment]
> Secondly, our team’s product(closed alpha for now) is also using json-viewer, we need customize json style in many cases. We need also improve the styling system, my currently plan is to use @mui/material which is a popular library.

I suggest use tailwindcss (a popular libaray to build style https://tailwindcss.com/ ), it is better choice , better to custom style.

**Comment by Himself65** [comment]
> 

I was coding these days. I think we just need https://mui.com/system/getting-started/overview/ for the styling system. We don't need much more CSS, neither in mui or tailwinds

**Comment by erewhon** [comment]
Is there a plan, or desire, to add a prop that collapses the entire tree by default?  (Like the "collapsed" prop in react-json-view.)

**Comment by Himself65** [comment]
> Is there a plan, or desire, to add a prop that collapses the entire tree by default? (Like the "collapsed" prop in react-json-view.)

you can archive this by setting defaultInspectDepth and maxDisplayLength to a large number.

I'm not sure how entire you want for a tree. I think that will be enough for a screen

**Comment by erewhon** [comment]
That's an interesting idea.  (defaultInspect="*").  

I had tried defaultInspectDepth but it didn't seem to work.  I hadn't looked at the code before, but just did.  Maybe I'm missing something, but it looks like createJsonViewerStore ignores the props for defaultInspectDepth?

**Comment by Himself65** [comment]
> 

I see. It's a mistake. I will open a pr

**Comment by gregfenton** [comment]
Is this a thread where we can discuss additional features?

If so, I would be interested in having the ability to "sort alphabetically".

**Comment by gregfenton** [comment]
> you can archive this by setting defaultInspectDepth and maxDisplayLength to a large number.

Is there an API or Options doc page for all of these settings?

**Comment by gregfenton** [comment]
Maybe put a link to that in the README as a "v1.0" of the "docs"?

Greg Fenton.

**Comment by bdsoha** [comment]
> I was coding these days. I think we just need https://mui.com/system/getting-started/overview/ for the styling system. We don't need much more CSS, either in mui or tailwinds.

@Himself65 Using a *MUI* would add a lot of dependencies for people who are using alternative frameworks like http://chakra-ui.com. Any thoughts?

**Comment by Himself65** [comment]
> > > I was coding these days. I think we just need https://mui.com/system/getting-started/overview/ for the styling system. We don't need much more CSS, either in mui or tailwinds.
> > 
> > 
> > @Himself65 Using a _MUI_ would add a lot of dependencies for people who are using alternative frameworks like http://chakra-ui.com. Any thoughts?
> 
> This is a tough question for any component library. I think abstracting a UI-replaceable component library is kind of hard for now. But we could export an unstyled JSON-viewer component in the future, for example
> 
> ```tsx
> import { withStyledJsonViewer } from '@textea/json-viewer'
> 
> const StyledJsonViewer = withStyledJsonViewer({
>   Box: (props) => (<Box /* you handle the props to a third-party UI library*/></Box>)
> })
> 
> // or even further, we port the UI to other library like tailwind css, or chakra ui
> import { withStyledJsonViewer, TailwindCSSMixture } from '@textea/json-viewer'
> const TailWindCSSJsonViewer = withStyledJsonViewer(TailwindCSSMixture)
> ```

This might be a V3 roadmap, I think. Because we need to rewrite the whole code again to remove the UI hard binding!

**Comment by pengbins** [comment]
> > I was coding these days. I think we just need https://mui.com/system/getting-started/overview/ for the styling system. We don't need much more CSS, either in mui or tailwinds.
> 
> @Himself65 Using a _MUI_ would add a lot of dependencies for people who are using alternative frameworks like http://chakra-ui.com. Any thoughts?

![image](https://user-images.githubusercontent.com/1439218/207020252-272c5f83-8113-4b1b-87be-b8ed44a8d43a.png)

About 97% BUNDLE SIZE is mui .

**Comment by kirill-linnik** [comment]
hey, I cannot find it that easy but:
- how can I "expand all" on demand? (say, my depth is 3, but sometimes I want to open it all)
- how can I edit keys?

and... thank you for your effort!

**Comment by rtritto** [comment]
Can be a good idea to replace `zustand` with `recoil`? Maybe to gain performance (idk) or other feathures

**Comment by mashirozx** [comment]
I wonder, this lib is expected to be a simple component plugin to display JSON view, so there is no need of global state management lib. In my use case, I didn't use `zustand` lib in my project (I use others instead), and the import of `json-viewer` result in the useless `zustand` lib in my project build bundle. Can we consider remove the  `zustand` lib and use react's original methods like context provider to replace that?

**Comment by GeorgiKeranov** [comment]
> Is there a plan, or desire, to add a prop that collapses the entire tree by default? (Like the "collapsed" prop in react-json-view.)

I was having the same problem and resolved it by adding `defaultInspectDepth={0}` which collapses the root object by default :)

**Comment by Himself65** [comment]
> Can be a good idea to replace `zustand` with `recoil`? Maybe to gain performance (idk) or other feathures.
> 
> ### Edit
> For state management, Atoms approach is faster than Flux and Proxy ones because is closer to the React state ([source](https://blog.logrocket.com/jotai-vs-recoil-what-are-the-differences)). `recoil` and `jotai` use Atoms approach. `jotai` handles garbage collectore automatically ([source](https://blog.openreplay.com/top-6-react-state-management-libraries-for-2022)) so as performace is better and bundle size is less than `recoil`.
> 
> `zustand` can be replaced with `jotai`.
> 
> Related PR #167
> 
> FYI @Himself65

Thanks for the reply but I have no longer maintain this project since the CEO has arrears in the salary since 3 months ago

**Comment by forrestbao** [comment]
@rtritto and community: @pionxzh has been in charge of this library for a while, please copy him if you have future suggestions.

**Comment by mashirozx** [comment]
> @rtritto and community: @pionxzh has been in charge of this library for a while, please copy him if you have future suggestions.
> 
> We welcome contributions to this library from anyone. At the end of the day, the work was pioneered by [mac-s-g](https://github.com/mac-s-g/react-json-view).

hummm, is this the CEO?🫣

**Comment by Himself65** [comment]
Closing as this won't be finished in this repo.

Please keep an eye on the new fork https://github.com/Himself65/data-viewer. I will keep maintaining that.
