### ISSUE TITLE
[docs] bad links in README and project pages

### ISSUE THREAD

**Issue by gregfenton** [TexteaInc/json-viewer#110]
- The README page has a link to a 404 page:
   - ![image](https://user-images.githubusercontent.com/4407559/199983951-ccee59ed-7645-4bc8-9912-2fcb7de1efc3.png)

- The project page links to a site that does not exist:
   - ![image](https://user-images.githubusercontent.com/4407559/199984232-b57390fc-2147-49c3-a4b5-fda9cfc0fa46.png)

Happy to help out with a PR, but I'm not sure where these should link to...

**Comment by Himself65** [comment]
oh, the problem is I change the DNS hoster from google dns to cloudflare

**Comment by Himself65** [comment]
I will fix this soon. Sorry for that

**Comment by Himself65** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/14026360/200062420-01506e81-4505-4168-8cfa-e0516c19c973.png">

Fixed

**Comment by Himself65** [comment]
please wait for a while or clear your browser cookie
