### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by Crown1991** [TexteaInc/json-viewer#115]
ERROR in ./node_modules/@textea/json-viewer/dist/index.mjs 89:42
Module parse failed: Unexpected token (89:42)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| const createJsonViewerStore = props => create(combine({
|   // provided by user
>   enableClipboard: props.enableClipboard ?? true,
|   indentWidth: props.indentWidth ?? 3,
|   groupArraysAfterLength: props.groupArraysAfterLength ?? 100,
 @ ./src/containers/AutoML2/components/ReportDetail/index.js 36:0-49 357:24-34
 @ ./src/containers/AutoML2/components/ReportDrawer/index.js
 @ ./src/containers/AutoML2/TaskManage/index.js
 @ ./src/router.js
 @ ./src/index.js

![E53CBF72-9E86-485D-B985-55AEF6C6BE2A](https://user-images.githubusercontent.com/20311089/200766439-1b5448d0-02e1-446a-bbc1-10cc7deb2981.png)

**Comment by Himself65** [comment]
We use es2020 as output, I think your babel doesn’t support that feature 

Try to add @babel/plugin-proposal-nullish-coalescing-operator
