### ISSUE TITLE
Husky dependency

### ISSUE THREAD

**Issue by Banner-Keith** [TexteaInc/json-viewer#12]
post install script for husky fails if your package.json file is not in the same directory as .git.

There would need to be some kind of workaround for that or potentially removing the post install script in the distributed package. I assume it is used for developing json-viewer and not for end users of the package, but I'm not sure.

**Comment by Himself65** [comment]
Yeah, it's for developing json-viewer, because it's for commit message and code style checking. 

I follow the husky document that skips husky on the user side
https://typicode.github.io/husky/#/?id=yarn-2

Maybe we should find a better way to do this. I'm not sure because I never see the error in my team member's workspace

**Comment by Banner-Keith** [comment]
It looks like some people have had success with using prepare.

https://github.com/typicode/husky/issues/884

**Comment by Himself65** [comment]
I'm not familiar with these hook commands, honestly. I will keep current because I haven't received any error reports.
But you're welcome to contribute! thank u

**Comment by Banner-Keith** [comment]
It looks like that is how webpack is doing it. https://github.com/webpack/webpack/blob/main/package.json
If you'd like I can open a PR with the change, or when you have time you can try switching it to prepare and make sure it doesn't break your workflow.

**Comment by Himself65** [comment]
> It looks like that is how webpack is doing it. https://github.com/webpack/webpack/blob/main/package.json
> 
> If you'd like I can open a PR with the change, or when you have time you can try switching it to prepare and make sure it doesn't break your workflow.

Yes, thanks for your contribution

**Comment by Banner-Keith** [comment]
I found some more time to look into this. The package.json all looks correct, however I think however the publish is being done isn't firing the prepack script for whatever reason.

If prepack fires properly pinst will rename the postinstall script to _postinstall.

I can't see how you're doing the publish but that seems to be the source of the issue.

**Comment by Himself65** [comment]
> I found some more time to look into this. The package.json all looks correct, however I think however the publish is being done isn't firing the prepack script for whatever reason.
> 
> 
> 
> If prepack fires properly pinst will rename the postinstall script to _postinstall.
> 
> 
> 
> I can't see how you're doing the publish but that seems to be the source of the issue.

the publish is automatically by GitHub ci 

https://github.com/TexteaInc/json-viewer/blob/main/.github/workflows/release-please.yml

**Comment by Banner-Keith** [comment]
I believe I figured out a fix.

**Comment by Himself65** [comment]
Landed in https://github.com/TexteaInc/json-viewer/commit/13aa82ff1fc7f720645c5b20b09fc30fbd6a0e40
