### ISSUE TITLE
createContext is not a function

### ISSUE THREAD

**Issue by Maximuschka** [TexteaInc/json-viewer#126]
Hi there,

Until version 2.11.0, json-viewer was working flawlessly for me. Since version 2.11.1, I get following runtime error:
![image](https://user-images.githubusercontent.com/32708605/207018744-849c6923-cdec-4d04-b5d9-2b5db422b0eb.png)

Following the call stack, the error is stemming from this line of code (dist/index.js:97):
`  const { useStore: useJsonViewerStore , useStoreApi: useJsonViewerStoreApi , Provider: JsonViewerProvider  } = createContext();
` 

We are using json-viewer in a React project with following (core) dependencies:
```
 "dependencies": {
    "@textea/json-viewer": "^2.12.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
  },
```

When downgrading to version 2.11.0 everything works fine again.

**Comment by Himself65** [comment]
I will check this later

**Comment by pionxzh** [comment]
Could you provide a minimum reproduction for us to identify the problem?

**Comment by Maximuschka** [comment]
Hi pionxzh,

Sorry for my delay in replying. I have tried to reproduce the bug both in a fresh React project and by isolating the root cause in our own app. But even if I strip our app down to the abolute minimum, the createContext issue persists. Somehow the scope of the textea module is wrong. 

I have so far not been able to reproduce the bug outside of our environment. We are working on an ejected React app and at this point, I am suspecting, that the behavior is related to our highly customized webpack configuration. But I will have to dig deeper into it.

I will update you, as soon as I have news.

Thanks and best regards

**Comment by pionxzh** [comment]
This `createContext` API call has been removed from the codebase (#250).
I will close this as it shouldn't be a problem anymore.
