### ISSUE TITLE
Use a different label for "Items" count in objects

### ISSUE THREAD

**Issue by philer-jambit** [TexteaInc/json-viewer#128]
Currently with the `displayObjectSize` option enabled (default), both arrays and objects have a label "*N* Items" to indicate the size of the collection.

I (and at least one other person 😉) find it confusing that these are labeled the same for arrays and objects. My suggestions:

1. Use a different label for objects, such as "Entries", "Properties" or "Keys".
1.1. Cherry on top: make it configurable for objects and arrays respectively.
2. Make it possible to toggle `displayObjectSize` and `displayArraySize` (new) independently.

However you decide, thanks for your work on this project!

**Comment by pionxzh** [comment]
Here is an example for people from the search engine.

### Document
Check `displaySize` in the [document/api](https://viewer.textea.io/apis)
Basically, it's simple, just pass a function to it to customize the behavior by returning a boolean.

### Example
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v2-bvftgp?file=pages%2Findex.js)
