### ISSUE TITLE
Using NextJS 13.1: Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by mastepanoski** [TexteaInc/json-viewer#131]
I have the following code:

`/* 3rd party libraries & components */
import React from 'react'
import { NamedColorspace, JsonViewer } from '@textea/json-viewer'

/* Local libraries & components */

export const ocean: NamedColorspace = {
  scheme: 'Ocean',
  author: 'Chris Kempson (http://chriskempson.com)',
  base00: '#2b303b',
  base01: '#343d46',
  base02: '#4f5b66',
  base03: '#65737e',
  base04: '#a7adba',
  base05: '#c0c5ce',
  base06: '#dfe1e8',
  base07: '#eff1f5',
  base08: '#bf616a',
  base09: '#d08770',
  base0A: '#ebcb8b',
  base0B: '#a3be8c',
  base0C: '#96b5b4',
  base0D: '#8fa1b3',
  base0E: '#b48ead',
  base0F: '#ab7967',
}

export interface CodeViewerProps {
  content: any
}

const CodeViewer: React.FC<CodeViewerProps> = ({ content }) => {
  return (
    <>
      <JsonViewer theme={ocean} value={content} style={{ marginTop: '10px' }} />
    </>
  )
}

export default CodeViewer`

And I get the exception "Module not found: Default condition should be last one"  when a I tried to build the project with NextJS.

**Comment by vladiisakov** [comment]
same for me

**Comment by vladiisakov** [comment]
@mastepanoski seems like its the last patch cause this issue, just use 2.12.0 version and it should be fine

**Comment by pionxzh** [comment]
This should have been fixed in https://github.com/TexteaInc/json-viewer/commit/9c8fda627fc892f002e3baef85eb686fcf1fbb72.
