### ISSUE TITLE
Module not found: Error: Can't resolve '@textea/dev-kit/utils' in 'F:\code\testplatformweb\node_modules\@textea\json-viewer\dist'

### ISSUE THREAD

**Issue by jayt1001** [TexteaInc/json-viewer#133]
version:2.12.2
![image](https://user-images.githubusercontent.com/29675005/209538837-18c93679-cc80-4bfc-a26c-4a8de513d62b.png)

**Comment by kuntik17** [comment]
Same here...

Cannot find module: '@textea/dev-kit/utils'. Make sure this package is installed.

You can install this package by running: yarn add @textea/dev-kit/utils.

**Comment by DGLcsGaming** [comment]
Same issue here.

**Comment by samhuk** [comment]
Hitting this too. I think that it's because it got put as a dev dependency, so when you npm install, it doesn't come along.

I think it's just an oopsie. Moving it from devDependencies to dependencies in package.json will fix this.

**Comment by forrestbao** [comment]
It seems that `@textea/dev-kit` is only used once in json-viewer.

https://github.com/TexteaInc/json-viewer/blob/a7e0dfd90150f008abe6f1a18924b9ba0199160a/src/stores/typeRegistry.tsx#L2

https://github.com/TexteaInc/json-viewer/blob/a7e0dfd90150f008abe6f1a18924b9ba0199160a/src/stores/typeRegistry.tsx#L77

And `DevelopmentError` does something very simple: 

```
export class DevelopmentError extends Error {
  constructor (message?: string) {
    super(
      message
        ? `${message}\n`
        : '' +
        'The behavior is not expected and not allowed.\n' +
        'If you see this in development, please fix the error ASAP.\n' +
        'If you see this in production, please contract our customer service.\n'
    )
  }
}
```

So I will just throw a simple string and remove `@textea/dev-kit` from the dependency.

**Comment by chrmoritz** [comment]
But shouldn't all the `eslint-*` be devDependencies instead of normal dependencies through?
