### ISSUE TITLE
Allow valueTypes Pre/PostComponent without Component

### ISSUE THREAD

**Issue by chilltemp** [TexteaInc/json-viewer#136]
Feature Requests AND/OR:  
* A) I'd like to be able to specify a PostComponent (or Pre) while using the built in types.
* B) Expose the built in types so that they can be reused.

```
export type DataType<ValueType = unknown> = {
  is: (value: unknown, path: Path) => boolean
  Component: React.ComponentType<DataItemProps<ValueType>>
  Editor?: React.ComponentType<EditorProps<ValueType>>
  PreComponent?: React.ComponentType<DataItemProps<ValueType>>
  PostComponent?: React.ComponentType<DataItemProps<ValueType>>
}
```

Use cases:
* Add links to url's while retaining the normal string appearance.
```
// Sample A
valueTypes={[{
  is: (props) => typeof props === 'string' && props.value.startsWith('https://'),
  PostComponent: (props) => <Link href={props.value}>open <Icon /></Link>,
}]}
// Sample B
valueTypes={[{
  is: (props) => typeof props === 'string' && props.value.startsWith('https://'),
  Component: JSONStringValue,
  PostComponent: (props) => <Link href={props.value}>open <Icon /></Link>,
}]}
```
* Add local date/time conversion
```
// Sample A
valueTypes={[{
  is: (props) => typeof props === 'string' && isDate(props.string),
  PostComponent: (props) => <span>{toLocalDate(props.value)}</span>,
}]}
// Sample B
valueTypes={[{
  is: (props) => typeof props === 'string' && isDate(props.string),
  Component: JSONStringValue,
  PostComponent: (props) => <span>{toLocalDate(props.value)}</span>,
}]}
```

**Comment by chilltemp** [comment]
Looking at your source code, another solution might be to expose `useTypeComponents()` or `matchTypeComponents()`, but this risks a circular reference.  Perhaps a variant that can only see (or prefers) the `predefined()` types?

```
// value = empty string, and an empty path hopefully returns the string DataType.
// added an options arg to prevent circular references
const stringDataType = useTypeComponents('', [], { predefinedOnly: true });

return <JsonViewer value={data} valueTypes={[{
  ...stringDataType,
  is: (props) => typeof props === 'string' && isDate(props.string),
  PostComponent: (props) => <span>{toLocalDate(props.value)}</span>,
}]} />;
```

**Comment by pionxzh** [comment]
B) Isn't `DataType` already been exported?

**Comment by pionxzh** [comment]
I might need some time to look into it. But it's a good suggestion for extendability.

**Comment by chilltemp** [comment]
> B) Isn't `DataType` already been exported?

Not that I could find.  I see the type handlers/components being created in [/src/stores/typeRegistry.tsx:  predefined](https://github.com/TexteaInc/json-viewer/blob/main/src/stores/typeRegistry.tsx#L86).  But couldn't find a way to access that.  Hence, my second message about exposing `useTypeComponents()` or `matchTypeComponents()`.

Thanks for considering this!  What I've done for now is to create a less functional string value component to use
