### ISSUE TITLE
Can't import the named export 'Box' from non EcmaScript module\Can't import the named export 'jsxs' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by jayt1001** [TexteaInc/json-viewer#138]
v:2.12.4
![image](https://user-images.githubusercontent.com/29675005/210290651-a264b0d0-4658-4c08-abb7-5480b1018206.png)

![image](https://user-images.githubusercontent.com/29675005/210290589-8a4c60ee-f715-4f0f-b113-e52302f812a9.png)

**Comment by mvadari** [comment]
@jayt1001 how did you resolve this error?

**Comment by pionxzh** [comment]
Looks like similar to https://github.com/polkadot-js/extension/issues/621#issuecomment-759341776
