### ISSUE TITLE
How to set displayArrayKey,onSelect

### ISSUE THREAD

**Issue by jayt1001** [TexteaInc/json-viewer#139]
Thank you very much！
How to set displayArrayKey,onSelect :
![image](https://user-images.githubusercontent.com/29675005/210306547-b266e855-9ea2-4e0c-bd1a-ec7d9a4937aa.png)

**Comment by pionxzh** [comment]
Are you still using V1?
It should be like
```js
<ReactJsonView
    onSelect={handleSelect}
    displayArrayKey={true}
/>

**Comment by jayt1001** [comment]
> Are you still using V1? It should be like
> 
> ```js
> <ReactJsonView
>     onSelect={handleSelect}
>     displayArrayKey={true}
> />
> ```
I want to use it in V2

**Comment by jayt1001** [comment]
I want to use it in V2
