### ISSUE TITLE
Bundle size too large

### ISSUE THREAD

**Issue by CNFeffery** [TexteaInc/json-viewer#140]
How to effectively reduce the bundle size after using json-viewer.
![image](https://user-images.githubusercontent.com/49147660/210694944-51db0b29-81f6-4a8e-952f-ad0b01052cc5.png)

**Comment by rtritto** [comment]
Move all `@emotion/*` and `@mui/*` dependencies to peer dependencies?

**Comment by pionxzh** [comment]
> Move all `@emotion/*` and `@mui/*` dependencies to peer dependencies?

I think you are right. They should be moved out according to https://github.com/mui/material-ui/issues/35006

**Comment by pionxzh** [comment]
`@mui/icons-material` has been removed in [v2.13.0](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.13.0)

**Comment by pionxzh** [comment]
> > Move all `@emotion/*` and `@mui/*` dependencies to peer dependencies?
> 
> I think you are right. They should be moved out according to [mui/material-ui#35006](https://github.com/mui/material-ui/issues/35006)

The issue is that I'm worrying about moving them to peer is considered a **BREAKING** change.
What do you guys think? 😮‍💨

**Comment by rtritto** [comment]
Yes, it's a breaking change.
Peer dependencies should be added to install commands on README

**Comment by pionxzh** [comment]
We might do a breaking change in #185 to move `emotion` to the peer after CNY, which will bump the major to V3.
Umm `@mui` will also be moved, I think.
