### ISSUE TITLE
Remove deprecated code of `zustand`

### ISSUE THREAD

**Issue by rtritto** [TexteaInc/json-viewer#144]
Console output:
```console
[DEPRECATED] zustand/context will be removed in the future version. Please use `import { createStore, useStore } from "zustand"` for context usage. See: https://github.com/pmndrs/zustand/discussions/1180
[DEPRECATED] default export is deprecated, instead import { create } from'zustand'
```

Related migration guide:
- [to v4](https://github.com/pmndrs/zustand/blob/main/docs/migrations/migrating-to-v4.md)
- [context]( https://github.com/pmndrs/zustand/discussions/1180)

**Comment by mashirozx** [comment]
I wonder, this lib is expected to be a simple component plugin to display JSON view, so there is no need of global state management lib. In my use case, I didn't use `zustand` lib in my project (I use others instead), and the import of `json-viewer` result in the useless `zustand` lib in my project build bundle. Can we consider remove the  `zustand` lib and use react's original methods like context provider to replace that?

**Comment by pionxzh** [comment]
I will look into it. I agree that we might not need a state management tool here.
I just checked the size of `zustand` is [1.1kb](https://bundlephobia.com/package/zustand@4.3.2). And `jotai` is [2.3kB](https://bundlephobia.com/package/jotai@2.0.0).

@rtritto Are you still working on #167?
I will also need some of your input and comments on this 🙏

**Comment by rtritto** [comment]
> @rtritto Are you still working on https://github.com/TexteaInc/json-viewer/pull/167?

No, I'm still locked.

We can try to remove the store manager in favor of native React functions. Maybe there are some reasons why the store manager is used in v1.

First we need to analyze current use cases (related to behaviors of hooks, states, render, re-render etc) with [jotai ones](https://jotai.org/docs/basics/comparison).

**Comment by pionxzh** [comment]
We got rid of the annoying deprecation message in [v2.14.1](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.14.1). 🎉
