### ISSUE TITLE
Remove deprecated message in `npm`

### ISSUE THREAD

**Issue by rtritto** [TexteaInc/json-viewer#145]
Console output:
```console
@textea/json-viewer@npm:2.12.4 is deprecated: https://twitter.com/himseIf_65/status/1608526306249179137
```

npm: [@textea/json-viewer](https://www.npmjs.com/package/@textea/json-viewer)

**Comment by forrestbao** [comment]
@rtritto, thanks for letting us know. We are working on it. Thank you for your attention on Json-viewer. We at Textea are actively maintaining it.

**Comment by pionxzh** [comment]
It should be gone in `v2.13.0`+.
