### ISSUE TITLE
How to set displayArrayKey,onSelect in v2

### ISSUE THREAD

**Issue by jayt1001** [TexteaInc/json-viewer#150]
I want to use it in V2：
![image](https://user-images.githubusercontent.com/29675005/211989361-b85281a1-350a-44d2-b995-1e47accb51de.png)

**Comment by pionxzh** [comment]
V2 does not support these 2 props. Please check [/src/type.ts](https://github.com/TexteaInc/json-viewer/blob/main/src/type.ts) for all the options.
