### ISSUE TITLE
Handle props and styles

### ISSUE THREAD

**Issue by rtritto** [TexteaInc/json-viewer#152]
In `@mui/material`, in complex Components, some properties (with styles) can be applied specifing the nested component level.

For example, the [Select](https://mui.com/material-ui/api/select) component includes [Menu](https://mui.com/material-ui/api/menu) and [MenuList](https://mui.com/material-ui/api/menu-list) components:
_Both_ can be customized by this way:
```jsx
<Select
  ...,  // Select props
  sx={
    ...  // Select styles
  },
  MenuProps={{
    autoFocus: true,  // Menu prop
    sx={
      ...  // Menu styles
    },
    MenuListProps: {
      disablePadding: true,  // MenuList prop
      sx={
        ...  // MenuList styles
      }
    }
  }}
>
  ...
</Select>
```

Respectively, for example:
```jsx
<JsonViewer
  ...,  // JsonViewer props
  sx={
    ...  // JsonViewer styles
  },
  DataKeyPairProps={{
    ...,  // Box data-key-pair props
    sx: {
      ...  // Box data-key-pair styles
    },
    DataObjectProps: {
      ...,  // Box data-object props
      sx: {
        ...  // Box data-object styles
      },
    }
  }}
/>
```

**Comment by pionxzh** [comment]
This request will be tracked by #266. But the similar nested deep configuring won't be provided.
Reasons:
1. `DataKeyPair` and `Object` and other components are not public API; we also don't have the plan to expose them.
2. It's encouraged to use the `data-object` `data-key-pair`... classes to customize the appearance. Deep configuration won't provide users the chance to customize all the small details of the JSON-View.
3. I couldn't think of any other use cases to pass something other than `sx`/`style` to some component inside.

~~ChatGPT died, I spent much more time writing this long text than the implementation~~ 🤣
