### ISSUE TITLE
'JsonViewer' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by pengbins** [TexteaInc/json-viewer#16]
```
$ npx create-react-app  demo  --template redux-typescript
$ cd demo
$ npm install @textea/json-viewer --save
$ vim src/App.tsx      

import JsonViewer from '@textea/json-viewer';

function App() {
  const src = {'aaa': 'bbb'};
  return (
    <div className="App">
        <JsonViewer src={src}  />
    </div>
  );
}

export default App;

$ npm run build

TS2786: 'JsonViewer' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<ReactJsonViewProps, any, any> | null' is not a valid JSX element.
    Type 'Component<ReactJsonViewProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<ReactJsonViewProps, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'ReactNode' is not assignable to type 'Element | null'.
            Type 'undefined' is not assignable to type 'Element | null'.
     5 |   return (
     6 |     <div className="App">
  >  7 |         <JsonViewer src={src}  />
       |          ^^^^^^^^^^
     8 |     </div>
     9 |   );
    10 | }

```

**Comment by pengbins** [comment]
Which componet should I import ?  
ReactJson  or  JsonViewer  ?

**Comment by Himself65** [comment]
seems like a type issue

**Comment by Himself65** [comment]
Looks weird, I ran success on my mac

```shell
➜  code cd demo
➜  demo git:(main) npm install @textea/json-viewer --save
npm WARN ERESOLVE overriding peer dependency

added 57 packages, and audited 1498 packages in 5s

218 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  demo git:(main) ✗ code src/App.tsx
➜  demo git:(main) ✗ npm run build

> demo@0.1.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  92.4 kB  build/static/js/main.eedbeef1.js
  1.78 kB  build/static/js/787.f055211e.chunk.js
  264 B    build/static/css/main.e6c13ad2.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
```

**Comment by pengbins** [comment]
It will fail on linux, using docker can replay this issue.

```
docker run -ti --rm -v "$PWD/":/demo   -w /demo   node:18.9.0-bullseye     bash
```

**Comment by Himself65** [comment]
Could you please print the package.json?

**Comment by Himself65** [comment]
> It will fail on linux, using docker can replay this issue.
> 
> ```
> docker run -ti --rm -v "$PWD/":/demo   -w /demo   node:18.9.0-bullseye     bash
> ```

I tried, no bugs for me

**Comment by Himself65** [comment]
I get the error output

**Comment by Himself65** [comment]
Upstream: https://github.com/facebook/flux/issues/563

**Comment by pengbins** [comment]
Maybe I should just wait for https://github.com/TexteaInc/json-viewer/issues/3  ?

**Comment by Himself65** [comment]
> Maybe I should just wait for #3 ?

you can use "overwrite" field to make this https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

Or use other package manager

**Comment by Himself65** [comment]
> Maybe I should just wait for #3 ?

Yes, that will fix this. But still need time

**Comment by pengbins** [comment]
> > Maybe I should just wait for #3 ?
> 
> you can use "overwrite" field to make this https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
> 
> Or use other package manager

Ok, thanks.

**Comment by Himself65** [comment]
Please wait for https://github.com/TexteaInc/json-viewer/pull/18 to land. And thanks for reporting bugs

**Comment by Himself65** [comment]
You can try https://github.com/TexteaInc/json-viewer/pull/18 now. I've finished the basic usage of JSON viewer. 100% written with Hooks and zustand

**Comment by pengbins** [comment]
https://socket.dev/npm/package/@textea/json-viewer/dependencies/1.24.5
It seems flux still in the dependencies list.

**Comment by Himself65** [comment]
> https://socket.dev/npm/package/@textea/json-viewer/dependencies/1.24.5 It seems flux still in the dependencies list.

No, please try 2.0.0-alpha.x. 1.x is old version patch

**Comment by Himself65** [comment]
https://stackblitz.com/edit/textea-json-viewer-v2?file=pages%2Findex.js
