### ISSUE TITLE
v2 replacement for groupArraysAfterLength?

### ISSUE THREAD

**Issue by davidlougheed** [TexteaInc/json-viewer#19]
I realize v2 is still in early alpha, but I am trying to upgrade my project to react 18 (and so I've had to switch from `react-json-view` to this) and I'm wondering if there is a replacement for the `groupArraysAfterLength` parameter in v2, since it doesn't seem to work the same way. 
Thanks!

**Comment by Himself65** [comment]
> 

I just finished the basic usage of v2, other props are still working on it. 

V2 will support all of the old props when it is stable. Thanks

**Comment by davidlougheed** [comment]
great, thanks for the prompt response!

**Comment by Himself65** [comment]
try it https://stackblitz.com/edit/textea-json-viewer-v2?file=package.json,pages%2Findex.js%3AL43

**Comment by davidlougheed** [comment]
@Himself65 it doesn't work the same way as in v1; in v1 it would collapse the array segments and you could click on them to expand them - the use case here was with objects with long array properties – the main objects could be expanded, but the long arrays could be collapsed

**Comment by Himself65** [comment]
> @Himself65 it doesn't work the same way as in v1; in v1 it would collapse the array segments and you could click on them to expand them - the use case here was with objects with long array properties – the main objects could be expanded, but the long arrays could be collapsed

thanks for trying, let me read the old code to make sure they have the same behavior
