### ISSUE TITLE
Fix Cyclic Dependency

### ISSUE THREAD

**Issue by anthonyalayo** [TexteaInc/json-viewer#202]
`DataKeyPair` calls:

`import { useTypeComponents } from '../stores/typeRegistry';`

`typeRegistry` calls:

`import { ObjectType, PostObjectType, PreObjectType } from '../components/DataTypes/Object';`

`Object` calls:

`import { DataKeyPair } from '../DataKeyPair';`

**Comment by Himself65** [comment]
This is expected behavior. It won't make the error. And you cannot remove the cyclic dependency. There's always a loop call

But I think I can make it a lazy import
