### ISSUE TITLE
Adding support for configuring key and value color

### ISSUE THREAD

**Issue by anthonyalayo** [TexteaInc/json-viewer#233]
Hey team,

What do you think about allowing color to be configurable?

**Comment by pionxzh** [comment]
You can pass a [Base16](https://github.com/chriskempson/base16) theme to `theme`.
The color key for `key` will be `base07`. You might need to check the code for the mapping of value to color key.

Check the example here -> [base16.ts](https://github.com/TexteaInc/json-viewer/blob/main/src/theme/base16.ts)

**Comment by anthonyalayo** [comment]
Ah, I missed this. Thank you!
