### ISSUE TITLE
Allow specifying quotes or no quotes on copy to clipboard

### ISSUE THREAD

**Issue by anthonyalayo** [TexteaInc/json-viewer#234]
Hey team,

Right now, copy to clipboard quotes the value. Would it be possible to make that configurable?

In V1, [mac-s-g/react-json-view](https://github.com/mac-s-g/react-json-view), I used to be able to highlight text to get between the quotations. Now highlighting text is disabled, so there's no workaround.

Thanks,
Anthony

**Comment by pionxzh** [comment]
Could you give me an example of current behavior and the expected result?

> I used to be able to highlight text to get between the quotations. Now highlighting text is disabled

^ I don't get this~~ What do you mean? You should be able to highlight the text with #217.

**Comment by anthonyalayo** [comment]
Aha, I didn't realize a fix got merged :-) I was using the previous version. Thank you for the fix!
