### ISSUE TITLE
`onSelect` property removed v2.x

### ISSUE THREAD

**Issue by mfklauberg** [TexteaInc/json-viewer#237]
Hello,

Comparing the exposed component properties between v1 and v2, I noticed that the `onSelect` property was removed, but couldn't find any reference for this breaking change within the release notes changelog.

Was its removal intentional, and if not, would it be possible for it to be added back? If thats the case, I would be open to make the change and open a PR for it.

Thanks in advance.

**Comment by forrestbao** [comment]
Hi @mfklauberg, please go ahead to add it back and open a PR. Thank you very much for your contribution.

**Comment by mfklauberg** [comment]
Thanks, will start working on it asap

**Comment by mfklauberg** [comment]
Hi @forrestbao, opened #238 adding the feature back, thanks!
