### ISSUE TITLE
onMouseLeave the JSON tree collapses

### ISSUE THREAD

**Issue by OttlikG** [TexteaInc/json-viewer#239]
https://user-images.githubusercontent.com/2817762/220919620-494f8738-297e-4524-9776-b2ccc54224e5.mov

I think the best behaviour is to not collapse the JSON viewer, it result to a jarring behaviour.

I see the `setHover(null)` is the default behaviour.
https://github.com/TexteaInc/json-viewer/blob/main/src/index.tsx#L91

If we really need this it could be customisable.

**Comment by pionxzh** [comment]
Could you provide a minimum reproduction? It looks like you are using user-land code to collapse the whole viewer. JSON-Viewer itself should not have this kind of behavior. 🤔

**Comment by pionxzh** [comment]
I will close first as there is no further information.
