### ISSUE TITLE
Error: To load an ES module, set "type": "module" in the package.json or use the .mjs extension

### ISSUE THREAD

**Issue by mastepanoski** [TexteaInc/json-viewer#240]
I upgraded to version 2.14.0 from 2.13.1 and when I  build the project (Using nextjs+typescript), it triggers the following error:

    info  - Collecting page data ..(node:26596) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
    (Use `node --trace-warnings ...` to show where the warning was created)
    /home/myuser/prj/node_modules/@textea/json-viewer/node_modules/@mui/material/Paper/index.js:1
    export { default } from './Paper';
    ^^^^^^
    
    SyntaxError: Unexpected token 'export'
        at Object.compileFunction (node:vm:360:18)
        at wrapSafe (node:internal/modules/cjs/loader:1088:15)
        at Module._compile (node:internal/modules/cjs/loader:1123:27)
        at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
        at Module.load (node:internal/modules/cjs/loader:1037:32)
        at Module._load (node:internal/modules/cjs/loader:878:12)
        at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
        at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
        at async Promise.all (index 0)
        at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    
    > Build error occurred

If I downgrade to 2.12.1 it works.

**Comment by pionxzh** [comment]
You can use `transpilePackages` as a workaround first. 

```diff
// next.config.js
const nextConfig = {
  reactStrictMode: true,
+  transpilePackages: ['@textea/json-viewer'],
}
```

**Comment by Tarasikee** [comment]
Having the same issue after migrating to `Next13`

**Comment by jdssanil** [comment]
Having the same issue on Next v13. The workaround did NOT fix it.

**Comment by pionxzh** [comment]
> Having the same issue on Next v13. The workaround did NOT fix it.

Did you see a different error message?

**Comment by doomedramen** [comment]
![Screenshot 2023-03-06 at 18 19 13](https://user-images.githubusercontent.com/445964/223196969-45b418ff-cb6e-42cf-8510-3ddbe3aebe3e.png)
I am having the same issue

**Comment by doomedramen** [comment]
going to [2.12.5](https://www.npmjs.com/package/@textea/json-viewer/v/2.12.5) was the solution for me

**Comment by pionxzh** [comment]
[v2.14.1](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.14.1) has been released. Let me know if you still see the same build error.

**Comment by mastepanoski** [comment]
From v2.14.1 it works without using the workaround. So it is fixed at least for me.
