### ISSUE TITLE
Collapsable custom value fields

### ISSUE THREAD

**Issue by bladerunner2020** [TexteaInc/json-viewer#281]
We have a custom valueTypes to display images and multiline texts. How can we make them collapsable?

**Comment by pionxzh** [comment]
I wrote an example to display collapsable multiple images.
https://stackblitz.com/edit/textea-json-viewer-v2-cklgn6?file=pages/index.js

**Comment by bladerunner2020** [comment]
> Currently you need to have a value with deeper content(non-empty object, array with items...etc) and provide `PreComponent` and `PostComponent` to enable the collapsable feature.
> Btw, Can you share some example code here?

We have an embedded REST API tool that let you check the results of REST API requests to our server. Some of endpoints returns base64 image as data.  We convert them to images and display inline (it's rather experimental feature for us).

```javascript
  <JsonViewer
    rootName={false}
    displayDataTypes={false}
    value={result}
    valueTypes={[
      createDataType(
        (value, path) => (path.length === 1 && path[0] === 'status'
          && (value === 'success' || value === 'error')),
        ({ value }) => {
          if (value === 'success') return (<b><span style={{ color: 'green' }}>{value}</span></b>);
          if (value === 'error') return (<b><span style={{ color: 'red' }}>{value}</span></b>);
          return value;
        }
      ),
      createDataType(
        (value) => typeof value === 'string' && value.indexOf('data:image/png;base64') === 0,
        ({ value }) => (
          <img src={value} alt="" />
        )
      )
    ]}
  />
```

**Comment by bladerunner2020** [comment]
> I wrote an example to display collapsable multiple images.
> https://stackblitz.com/edit/textea-json-viewer-v2-cklgn6?file=pages/index.js

That's great! Thanks)

**Comment by pionxzh** [comment]
@bladerunner2020 based on your scenario, I think this example should be useful for you.
https://stackblitz.com/edit/textea-json-viewer-v2-collapsable-custom-value?file=pages%2Findex.js

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v2-collapsable-custom-value?file=pages%2Findex.js)
