### ISSUE TITLE
is it possible to format the unix timestamp output

### ISSUE THREAD

**Issue by jiangxiaoqiang** [TexteaInc/json-viewer#299]
when the json contains unix timestam, is it possible to format the unix timestamp to `YYYY-MM-dd` and show the formatted value(maybe the origin and formatted both)? I read the docs but did not found anywhere mention it.

**Comment by pionxzh** [comment]
I have explained more in the V3 document. For now, you will have to check the raw md file [here](https://github.com/TexteaInc/json-viewer/blob/v3.x/docs/pages/how-to/data-type.mdx), sorry for the inconvenience.

For this case, you shall be able to extend the string dataType to customize the appearance of a specific data type. I'm still working on finalizing the API to help user to customize it without friction.

**Comment by pionxzh** [comment]
I have added an example for this in #313. I expect to release V3 this week after proper testing.
