### ISSUE TITLE
Installation command in README is not completed

### ISSUE THREAD

**Issue by MartenMIK** [TexteaInc/json-viewer#322]
Thank you for the release!

When installing yesterdays new version and running the my usual vite build I get:
```
✘ [ERROR] Could not resolve "@mui/material"

    node_modules/@textea/json-viewer/dist/index.mjs:3:82:
      3 │ ... SvgIcon, createTheme, ThemeProvider, Paper } from '@mui/material';
        ╵                                                       ~~~~~~~~~~~~~~~

  You can mark the path "@mui/material" as external to exclude it from the bundle, which will remove this error.
```

When instead adding the previous version `@textea/json-viewer@2.17.2`, the build works fine and everything works as expected. Was there an error when moving `@mui/material` to peer dependecies? Or is this something wring about my build? (Other peer dependecies work fine)

**Comment by MartenMIK** [comment]
Indeed, thank you! Did not spot the update in the readme. 
I think this also needs to be added to the install lines of the other two package managers?

**Comment by pionxzh** [comment]
Oh I forgot to update the command, thanks for spotting that.
