### ISSUE TITLE
feat: collapse fields using an array of matcher functions

### ISSUE THREAD

**Issue by roshaans** [TexteaInc/json-viewer#326]
I have a very large JSON object which   I would like to allow my user's to inspect, but they do not need most of the information, so It would be great to programmatically be able to collapse and uncollapse fields.  

We can take an additional props for `expandedPaths: Path[]` and modify the DataItemProps to include `isExpanded`.

We can set the isExpanded field for every data item initially by matching it against expandedPaths and when rendering, check to see if `isExpanded` is true to expand/collapse.

Additionally, it would be even better to instead of taking a list of path's for `expandedPaths`, we take in a list of functions that validate a path `expandedPaths?: ((path: Path) => boolean)[])`, so that programmatically, we can accurately target custom fields whose full structure we do not know about in the begining for example an array of objects with many fields, but you'd only like to expand certain fields inside each element of the array, except you are not sure how many elements would be in the array in the start.

**Comment by pionxzh** [comment]
@roshaans let me know what you think~

**Comment by roshaans** [comment]
I agree with having the defaultInspectControl prop. For the meantime, I am most likely going to leverage another solution, but I appreciate your support.

**Comment by pionxzh** [comment]
There are some problems on the CI releasing. I will fix it and update a example for this.

**Comment by pionxzh** [comment]
You can check this demo.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v3-b4wgxq-k7qjan?file=pages%2Findex.js)
