### ISSUE TITLE
Hydration error Text content did not match

### ISSUE THREAD

**Issue by CodeStarrk** [TexteaInc/json-viewer#359]
I am having a hydration error simply from a ternary operator, what this code does is it views the JSON data, if the data that is being input in realtime is not of JSON format, then we wait and fallback to the previous valid JSON. What am I doing wrong?

![image](https://github.com/TexteaInc/json-viewer/assets/24924981/8c2b10ae-14c7-4b33-b141-03b26e15f368)

![image](https://github.com/TexteaInc/json-viewer/assets/24924981/844ccab8-558d-47a5-8f74-90723b64fa7a)

**Comment by pionxzh** [comment]
Could you provide a simple reproduction?

**Comment by CodeStarrk** [comment]
Hm wait nevermind, it has nothing to do with that condition, simply displaying it gives that error. I think it is an error with Zustand, the state management that I use, I have a default text and the localstorage saved text that kicks in, weird that it gives this error. sorry I think it has nothing to do with the Jsonviewer library 😅

Never had this happen before with Nextjs + Zustand so I thought it was the Jsonviewer, all is good

https://github.com/pmndrs/zustand/discussions/855
