### ISSUE TITLE
Submit input value on Enter key

### ISSUE THREAD

**Issue by kozlovskisarmands** [TexteaInc/json-viewer#396]
Hello! Would it be possible to add functionality that Enter key on input press submits the values instead of putting in a new line? And also outside click out of Input field, would close the editing process.
Thanks in advance :)

**Comment by pionxzh** [comment]
You are right. The current new line behavior is quite weird. And I think we can have an option to enable the clicking out.

**Comment by pionxzh** [comment]
I think this one can be achieved by extending the built-in editor. There is an `abortEditing` function in props that can be called to exit the editing state. Closing. 🙏
