### ISSUE TITLE
How to show the string with scaped values (normal new lines, quotes, etc)?

### ISSUE THREAD

**Issue by MiniSuperDev** [TexteaInc/json-viewer#412]
Like this viewer, when the string values show the string with scaped values 
![image](https://github.com/TexteaInc/json-viewer/assets/105388540/e2418f02-ad3d-4d89-b4ae-faa4bb370507)

Thanks

**Comment by pionxzh** [comment]
Hi, you can extend the built-in string type to wrap the text with `<pre>` element.

#### Docs
[Extend Built-in Data Types](https://viewer.textea.io/how-to/built-in-types#displaying-boolean-values-as-icons)

#### Examples
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v3-b4wgxq-emrafa?file=pages%2Findex.jsx)

![image](https://github.com/TexteaInc/json-viewer/assets/9910706/5b7e6e2d-ad27-4c90-b510-17d5afc98c66)

**Comment by MiniSuperDev** [comment]
@pionxzh Thanks, is there an easy way to preserve the collapseStringsAfterLength behavior?

**Comment by pionxzh** [comment]
Currently no, you can implement it real quick.
useState + length checking + onClick
