### ISSUE TITLE
Root object copy button and closing curly brace not respecting theme color

### ISSUE THREAD

**Issue by Roundaround** [TexteaInc/json-viewer#441]
It seems like the built-in theming is missing for a few elements. In particular, the copy button and the closing curly brace for the root object don't receive any styling from base07 like the rest of the text.

![Screenshot from 2024-01-23 16-27-57](https://github.com/TexteaInc/json-viewer/assets/4167222/fb50b650-5034-4947-b44f-67c6712eedd9)
![Screenshot from 2024-01-23 16-28-20](https://github.com/TexteaInc/json-viewer/assets/4167222/91267b6c-df82-414e-b8fb-a00d0c76d527)

**Comment by pionxzh** [comment]
released `v3.3.1`
