### ISSUE TITLE
Hide array index

### ISSUE THREAD

**Issue by mysticek** [TexteaInc/json-viewer#490]
Hello, is there a way, how to hide array index numbers? Just show array items without 1, 2, 3... indexesM

**Comment by pionxzh** [comment]
There is a `KeyRenderer` config. But returning empty or `null` in that function would still show the colon which makes it look weird. 
![image](https://github.com/user-attachments/assets/c51c7c09-8f8e-4ea4-9ca3-c943cf651d01)

Things we can do to achieve what you want:
1. If the key is empty, hide the colon.
2. Wait for https://github.com/TexteaInc/json-viewer/issues/469

**Comment by pionxzh** [comment]
Another solution would be adding `data-type` to the dom so that you can do it in pure css.

**Comment by mysticek** [comment]
Thank you.

Second question - is possible to show commas after values?

**Comment by pionxzh** [comment]
Comma... I think this one can be added to the package. Can you submit another request for it?

**Comment by pionxzh** [comment]
#496 has added support for hiding arbitrary index/key. I will prepare a demo after it gets released.

**Comment by pionxzh** [comment]
released 3.5.0 with this feature. Let me prepare the demo this week.

**Comment by pionxzh** [comment]
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v3-b4wgxq-bw4r97?file=pages%2Findex.js)

![image](https://github.com/user-attachments/assets/7d56c120-f01a-411a-82b1-c7a4b49e781c)

Please check the demo with
1. hiding array index
2. show comma

Btw, you can also select and copy valid JSON without hiding the array index. Try it out!

**Comment by hatton** [comment]
This took me a while to figure out. Future self, to stop this component from adding index numbers before all array items, do this:

```
  const KeyRenderer: JsonViewerKeyRenderer = ({ path }) => {
    const last = path[path.length - 1];
    return Number.isInteger(last) ? null : last;
  };
  KeyRenderer.when = () => true;
  ```
  and then 
  ```
        <JsonViewer
        keyRenderer={KeyRenderer}
        ...
 ```

**Comment by pionxzh** [comment]
This is how it was done in the example above

```ts
const KeyRenderer = () => {
  return null;
};
KeyRenderer.when = ({ path }) => {
  /**
   * check if the key is a number.
   *
   * This can be wrong in some edge cases like Map.
   */
  return typeof path[path.length - 1] === 'number';
};
```
