### ISSUE TITLE
Improvement: Value Edit value restoring

### ISSUE THREAD

**Issue by kozlovskk** [TexteaInc/json-viewer#537]
Hello! 
Would it be possible to add extra icon to already existing (copy, edit) icons, which would restore edit to previous step?
Example: edit value of field **amount** from 320 -> 10. New icon would appear on hovering the field, which by pressing, we would revert the value 1 step back - from 10 to 320. If the value is back to original one, the icon disappears.
Can this be a new improvement, perhaps? In our line of work, we would appreciate this update. Thanks!

**Comment by pionxzh** [comment]
I think it is difficult to support this feature.
1. There is no easy way for users to customize the action buttons.
2. Reverting value can be troublesome, considering providing a universal solution for all users.

I can leave this issue open as a reminder to add the ability to customize the buttons.

**Comment by pionxzh** [comment]
I tried to implement the feature in a different way.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/textea-json-viewer-v3-b4wgxq-xa7j2z?file=pages%2Findex.js)

![chrome_4gC9lUZGK5](https://github.com/user-attachments/assets/cd088f85-41a0-4077-abee-d0f6a6755950)

https://stackblitz.com/edit/textea-json-viewer-v3-b4wgxq-xa7j2z?file=pages%2Findex.js

**Comment by kozlovskk** [comment]
This actually looks good. Is this available feature already? I would like to add it to our project.

**Comment by pionxzh** [comment]
It's available for V3 V4, simply copy over the example into your project, and it should work without problems.

However, this implementation is quite limited. Your data source needs to remain stable since it will restore the whole object, not just the "field". You can improve it by storing the changed path and its previous and new values and then applying the reverted changes back into the object.

**Comment by pionxzh** [comment]
Let me know if you need the improved version or if you need help understanding my rough explanation.

**Comment by pionxzh** [comment]
Considered this as completed
