### ISSUE TITLE
Wrong valueTypes.is type

### ISSUE THREAD

**Issue by xepozz** [TexteaInc/json-viewer#55]
I've tried to customise value with usage `valueTypes.is`, but it shows that I'm wrong.
<img width="884" alt="image" src="https://user-images.githubusercontent.com/6815714/191728524-431f3847-8010-4f67-b75a-3e4802f5be8a.png">
I think we need to change types declaration as the following. 
```diff
declare type DataType<ValueType = unknown> = {
-    is: (value: any) => value is ValueType;
+    is: (value: ValueType) => boolean;
    Component: React.ComponentType<DataItemProps<ValueType>>;
    Editor?: React.ComponentType<EditorProps<ValueType>>;
    PreComponent?: React.ComponentType<DataItemProps<ValueType>>;
    PostComponent?: React.ComponentType<DataItemProps<ValueType>>;
};
```
What do you think?

And here is my workaround:
```ts
is: ((value: unknown): any => typeof value === 'string' && value.startsWith('@')) as any,
```

**Comment by Himself65** [comment]
The reason is `is valueType` is a stronger type here

for example

<img width="951" alt="image" src="https://user-images.githubusercontent.com/14026360/191807265-c5ada625-a812-47b0-985c-ab987c31df96.png">

I'm creating a helper function that could help this

**Comment by Himself65** [comment]
I created a helper function that you won't think about this

<img width="887" alt="image" src="https://user-images.githubusercontent.com/14026360/191808156-07c1b0c5-ec88-4d7b-9a10-11a2713bd0b9.png">

**Comment by xepozz** [comment]
> I created a helper function that you won't worry about the type

Actually, the best way is to leave `is: (value: ValueType) => boolean`. There is no need to have `value is ValueType` as a return type. Semantically it's always `true`. Isn't it?

**Comment by xepozz** [comment]
@Himself65 up

**Comment by Himself65** [comment]
You might be right. I'm not sure how people really deal with this API

**Comment by xepozz** [comment]
Logically `is` is just a boolean getter. I don't see any reasons to restrict the return type as `value is T`
