### ISSUE TITLE
Caching Component still brings problems

### ISSUE THREAD

**Issue by xepozz** [TexteaInc/json-viewer#66]
Thanks for fixing https://github.com/TexteaInc/json-viewer/issues/62, but caching components still brings problems.
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/6815714/191831297-27ea02e7-5c49-43d3-ba84-1604bd1446da.png">

Here is snippet:
```ts
import {JsonViewer} from "@textea/json-viewer";
import * as React from "react";
import {useState} from "react";
import {Button} from "@mui/material";

export function IndexPage() {
    const data = [{'key': 'val1'}]

    const [i, setI] = useState(1);

    console.log('value outside closure', i)

    return (
        <>
            <JsonViewer
                value={data}
                valueTypes={[
                    {
                        is: (() => true) as any,
                        Component: (props) => {
                            return <Button onClick={() => {
                                console.log('value inside closure', i)
                                setI(i => i + 1)
                            }}>{i} time clicked</Button>;
                        },
                    },
                ]}
            />
        </>
    )
}
```

Clicking on button doesn't change component because of memoisation, but it should.
I don't see any reasons to cache it.

**Comment by Himself65** [comment]
I was meant to design the value type component as a pure component. So it won't re-render until the props change and shouldn't use external variables. 
But I decide to let the user do anything now. But just remind that `valueTypes` will call `registerType` everything if you do not wrap it with `useMemo` in the new PR

https://beta.reactjs.org/apis/react/useMemo

**Comment by xepozz** [comment]
Thanks it works better now
