### ISSUE TITLE
The browser field in package.json causes vite to fail to parse properly

### ISSUE THREAD

**Issue by 0xDing** [TexteaInc/json-viewer#84]
I'm using this package in a vite + react project and vite seems to be incorrectly reading  `"browser": "dist/browser.js"` from package.json as the load entry, resulting in an error.

Changing package.json to `{ "browser": { "vanilla": "dist/browser.js" }  }` may help with this issue.

Thanks

**Comment by Himself65** [comment]
Ok. thanks for reporting. I'm not using vanilla so I didn't realize that

**Comment by Himself65** [comment]
2.7.1 will fix this. Could u please try it again? Thank u

**Comment by Himself65** [comment]
Released
