### ISSUE TITLE
support define function to render key and value 

### ISSUE THREAD

**Issue by awkj** [TexteaInc/json-viewer#9]
Like https://www.npmjs.com/package/react-json-tree 
Have api 
- labelRenderer 
- valueRenderer

**Comment by Himself65** [comment]
yeah, I'm also thinking of adding some hooks like what you said.

**Comment by awkj** [comment]
Looking forward to your work

**Comment by Himself65** [comment]
Related: https://github.com/mac-s-g/react-json-view/issues/420

**Comment by Himself65** [comment]
you can pass keyRenderer like this now

```tsx
const KeyRenderer: JsonViewerKeyRenderer = ({ path }) => {
  return <del aria-label='I dont like this number'>&quot;{path.slice(-1)}&quot;</del>
}
KeyRenderer.when = (props) => props.value === 114.514
const IndexPage = () => {
  return (
    <JsonViewer
        value={src}
        keyRenderer={KeyRenderer}
    />
)}
```

It will be like this
![Screenshot from 2022-09-17 21-14-00](https://user-images.githubusercontent.com/14026360/190882649-217973f1-d077-426c-8962-1bb9407a7355.png)

**Comment by Himself65** [comment]
for the value type, you can pass

```tsx
valueTypes = {
  [
    {
      is: (value): value is string => typeof value === 'string' && value.startsWith('https://i.imgur.com'),
      Component: (props) => {
        return <img height="50px" src={props.value} alt={props.value}/>
      }
    }
  ]
}
```

This will be like this 

![Screenshot from 2022-09-17 21-27-02](https://user-images.githubusercontent.com/14026360/190882921-6675bf0f-f7d3-4334-8038-4f24b4b79970.png)

**Comment by awkj** [comment]
great , I had run it sucess,  support image is beyond expectation.

anyway, I want to inherit default render to custom it, have api ?

**Comment by Himself65** [comment]
> great , I had run it sucess, support image is beyond expectation.
> 
> anyway, I want to inherit default render to custom it, have api ?

give a example code? I don't understand

**Comment by Himself65** [comment]
Do you mean the subtyping, like imageUrl is a sub-type of string?
