### ISSUE TITLE
Editable property no longer functions

### ISSUE THREAD

**Issue by chadallard** [TexteaInc/json-viewer#92]
v 2.7.3
Setting property editable={true} (or leaving out as it should be default), the viewer doesn't appear to allow this property to work.
Rows are not editable by clicking on them, and no pencil icon appears. 

I see commit 69 made true by default so it's possible that the default "false" logic remained somewhere. 
https://github.com/TexteaInc/json-viewer/commit/66c8d68e08364a75d66fc4588edf963f1b62c4e4

**Comment by Himself65** [comment]
i will fix that soon

**Comment by Himself65** [comment]
checking this now

**Comment by Himself65** [comment]
Thanks for reporting. The patch will be landed in the next patch version
