### ISSUE TITLE
Line break for long strings

### ISSUE THREAD

**Issue by baartch** [TexteaInc/json-viewer#94]
I would like to ask, what you think about to add the CSS style `overflow-wrap: anywhere;` to `string` values.

If I have very long strings without spaces, the JSON viewer will stretch accordingly. And the part that is larger than the parent is hidden. I am not very happy about this behaviour.

![withoutOverflowWrap](https://user-images.githubusercontent.com/26668031/193203615-6ccaf52b-faec-4810-9abf-7045e782555c.png)

If I add `overflow-wrap: anywhere;` it looks like this:
![withOverflowWrap](https://user-images.githubusercontent.com/26668031/193203684-00c73734-031d-4d15-ae29-21af28e51ed5.png)

I added the CSS property directly in the Developer Tools of the browser. I wasn't able to find the right place in the source code.

What do you think about this?

**Comment by Himself65** [comment]
You re correct. I will fix it later

**Comment by Himself65** [comment]
The source code is here https://github.com/TexteaInc/json-viewer/blob/1da2b1faac2088f8b3bf635465045fa0ffc6738e/src/stores/typeRegistry.tsx#L201-L239
